Feature/new examples
qbeyond/terraform-azurerm-windows-vm pull request #4
Opened 2023-07-12 13:24 UTC by JesStruk

# Description

As discussed in #(issue) we need to support xxx. Therefore we changed yyy.

# Change overview (tick true):

- [ ] Changed minor things, so it is deployable via terraform
- [ ] Fix minor bugs
- [ ] Added examples

# Version information: 

- Previous Version: `0.0.0`

- Next Version based on [Semantic Versioning](https://semver.org/#summary) (see above): `1.0.0`

# How Has This Been Tested?

- [ ] Terraform Plan
- [ ] Tested by deployment via terraform apply

# Checklist:

- [ ] I have run tests and documented them above
- [ ] I have performed a self-review of my own code
- [ ] I have updated the documentation

2023-07-13 12:46 UTC, TheodorWulff commented on locals.tf
> +      name = coalesce(var.name_overrides.nic, replace(replace("nic-${var.virtual_machine_config.hostname}-${var.subnet.address_prefixes[0]}", ".", "-"), "/", "-")) # replace regex
use regex

2023-07-13 12:49 UTC, TheodorWulff commented on terraform.tf
> +provider "azurerm" {
remove this from the module. This should only belong in the code that calls this module.

2023-07-13 12:50 UTC, TheodorWulff requested changes
Added some comments

2023-07-13 14:34 UTC, QBY-ChristianHartmann commented on examples/basic/main.tf
> +        os_version = "latest"
is optional, leave out of basic example

2023-07-13 14:46 UTC, JesStruk commented on locals.tf
> +      name = coalesce(var.name_overrides.nic, replace(replace("nic-${var.virtual_machine_config.hostname}-${var.subnet.address_prefixes[0]}", ".", "-"), "/", "-")) # replace regex
replace uses now regex "/[./]/" - no double replace function

2023-07-13 14:50 UTC, QBY-ChristianHartmann commented on examples/basic/main.tf
> +        os_version = "latest"
is optional, leave out of example

2023-07-13 14:53 UTC, TheodorWulff requested changes
Minor bug in naming

2023-07-14 07:19 UTC, TheodorWulff submitted a review, later dismissed
Looks good now

2023-07-14 07:19 UTC, QBY-ThimoLimpert commented
Please change the readme, add the second example and provide a little bit more info then `easy to use `:D

2023-07-14 08:04 UTC, QBY-ThimoLimpert approved these changes

2023-07-14 08:06 UTC, QBY-ChristianHartmann approved these changes

2023-07-14 08:06 UTC, merged